export const GET_CURRENT_PAGE = 'GET_CURRENT_PAGE';

export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOADED = "AUTH_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_CAMPUS_COLLEGE = 'GET_CAMPUS_COLLEGE';
export const ADD_CAMPUS_COLLEGE = 'ADD_CAMPUS_COLLEGE';
export const DELETE_CAMPUS_COLLEGE = 'DELETE_CAMPUS_COLLEGE';
export const EDIT_CAMPUS_COLLEGE = 'EDIT_CAMPUS_COLLEGE';
export const UPDATE_CAMPUS_COLLEGE = 'UPDATE_CAMPUS_COLLEGE';
export const CAMPUS_COLLEGE_LOADER = 'CAMPUS_COLLEGE_LOADER';

export const GET_COLLEGE = 'GET_COLLEGE';
export const ADD_COLLEGE = 'ADD_COLLEGE';
export const DELETE_COLLEGE = 'DELETE_COLLEGE';
export const EDIT_COLLEGE = 'EDIT_COLLEGE';
export const UPDATE_COLLEGE = 'UPDATE_COLLEGE';
export const COLLEGE_LOADER = 'COLLEGE_LOADER';

export const GET_COLLEGE_COURSES = 'GET_COLLEGE_COURSES';
export const ADD_COLLEGE_COURSES = 'ADD_COLLEGE_COURSES';
export const DELETE_COLLEGE_COURSES = 'DELETE_COLLEGE_COURSES';
export const EDIT_COLLEGE_COURSES = 'EDIT_COLLEGE_COURSES';
export const UPDATE_COLLEGE_COURSES = 'UPDATE_COLLEGE_COURSES';
export const COLLEGE_COURSES_LOADER = 'COLLEGE_COURSES_LOADER';

export const GET_COURSE = 'GET_COURSE';
export const ADD_COURSE = 'ADD_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const COURSE_LOADER = 'COURSE_LOADER';

export const GET_DOCUMENT = 'GET_DOCUMENT';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const DOCUMENT_LOADER = 'DOCUMENT_LOADER';

export const GET_MAIN_CAMPUS = 'GET_MAIN_CAMPUS';
export const ADD_MAIN_CAMPUS = 'ADD_MAIN_CAMPUS'
export const DELETE_MAIN_CAMPUS = 'DELETE_MAIN_CAMPUS';
export const EDIT_MAIN_CAMPUS = 'EDIT_MAIN_CAMPUS';
export const UPDATE_MAIN_CAMPUS = 'UPDATE_MAIN_CAMPUS';
export const MAIN_CAMPUS_LOADER = 'MAIN_CAMPUS_LOADER';

export const GET_SATELLITE_CAMPUS = 'GET_SATELLITE_CAMPUS';
export const ADD_SATELLITE_CAMPUS = 'ADD_SATELLITE_CAMPUS';
export const DELETE_SATELLITE_CAMPUS = 'DELETE_SATELLITE_CAMPUS';
export const EDIT_SATELLITE_CAMPUS = 'EDIT_SATELLITE_CAMPUS';
export const UPDATE_SATELLITE_CAMPUS = 'UPDATE_SATELLITE_CAMPUS';
export const SATELLITE_CAMPUS_LOADER = 'SATELLITE_CAMPUS_LOADER';

export const GET_STUDENT = 'GET_STUDENT';
export const ADD_STUDENT = 'ADD_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const STUDENT_LOADER = 'STUDENT_LOADER';

export const GET_USER = 'GET_USER';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_LOADER = 'USER_LOADER';

export const GET_USER_DOCUMENT = 'GET_USER_DOCUMENT';
export const ADD_USER_DOCUMENT = 'ADD_USER_DOCUMENT';
export const DELETE_USER_DOCUMENT = 'DELETE_USER_DOCUMENT';
export const EDIT_USER_DOCUMENT = 'EDIT_USER_DOCUMENT';
export const UPDATE_USER_DOCUMENT = 'UPDATE_USER_DOCUMENT';
export const USER_DOCUMENT_LOADER = 'USER_DOCUMENT_LOADER';

export const TOP_ALERT = 'TOP_ALERT';

export const STUDENT_VALIDATION = 'STUDENT_VALIDATION';
export const EDUCATIONAL_ATTAINMENT_VALIDATION = 'EDUCATIONAL_ATTAINMENT_VALIDATION';
export const VALIDATION_LOADER = 'VALIDATION_LOADER';
export const REQUIRED_DOCUMENTS_VALIDATION = 'REQUIRED_DOCUMENTS_VALIDATION';
export const INTENDED_COURSE_VALIDATION = 'INTENDED_COURSE_VALIDATION';