export const studentData = {
    email: "asdasd@gmail.com",
    firstName: "Khhhhhhh",
    lastName: "Masdasasda",
    mobilePhoneNumber: 432142423,
    dateOfBirth: "08/02/01",
    placeOfBirth: "asdasd, Lagudasdana",
    gender: "Male",
    citizenship: "Filipino",
    barangay: "dfgdfg",
    municipality: "dfgdfg",
    province: "dfgdfg",
    zipCode: 4016,
    civilStatus: "gdfgdfgdfg",
    guardianName: "dasdasdasda",
    guardianAddress: "gfdgdfgdf",
    guardianMobileNumber: 45312312123,
    relationToGuardian: "dfgdfg",
    fathersName: ";kl;kl;gasd",
    mothersName: "Anasdasdasdal",
    elementaryName: "asdasd",
    elementaryTypeOfSchool: "asdasd",
    elementaryAddress: "Paasdasd",
    elementaryYearAttended: "2008",
    highschoolName: "Liceo de Pakil",
    highschoolTypeOfSchool: "Private",
    highschoolAddress: "Pakil Laguna",
    highschoolYearAttended: "2013",
    disability: "Communication Disablity",
    isIndigenouosPerson: false
  }